services:
  db:
    image: mysql:8.0
    container_name: fomokiller_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fomokiller
      MYSQL_USER: fkuser
      MYSQL_PASSWORD: fkpass
    #healthcheck para que el contenedor se reinicie si falla
    healthcheck:
      test: "mysqladmin ping -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD > /dev/null 2>&1" # El truco: > /dev/null 2>&1 silencia todo el texto (éxito y errores)
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

  server:
    build:
      context: ./Server
    container_name: fomokiller_server
    restart: always
    env_file:
      - ./Server/.env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy # ¡Perfecto! Esto esperará al healthcheck

  client:
    build:
      context: ./Client
    container_name: fomokiller_client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  db_data:
